# Generated by Django 5.0.6 on 2024-06-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_order_options_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Communication', 'Communication'), ('Computer', 'Computer'), ('Printer', 'Printer')], max_length=20, null=True),
        ),
    ]
